### ISSUE TITLE
Does this still work in Blender 3.6.4?

### ISSUE THREAD

**Issue by NOVALightLabs** [rbwendt/blender-add-mesh-fibonacci-sphere#3]
Love this idea but unable to get it to work in Blender 3.6.4 (so far...)

I installed the .py as an Add-On but under Mesh -> Add I do not see anything for a "Fibonacci Sphere".

Can you help detail what I might be doing wrong or how to get this to work?

Otherwise thank you for the efforts!
![Screenshot 2024-02-09 at 7 19 36 PM](https://github.com/rbwendt/blender-add-mesh-fibonacci-sphere/assets/159598676/a1fc065f-53f3-41bd-89da-0726343fda41)
![Screenshot 2024-02-09 at 7 19 30 PM](https://github.com/rbwendt/blender-add-mesh-fibonacci-sphere/assets/159598676/913a7b32-9c32-444a-b2d1-4f97b14345af)

**Comment by NOVALightLabs** [comment]
Okay, after a quick consult with ChatGPT it looks like the version number in the header was what needed to be fixed.

Change it to this:

bl_info = {
    "blender": (3, 6, 4),
    ...
}

Edit the .py file with a text editor. Save.

Uninstall, then reinstall, done.

![Screenshot 2024-02-09 at 7 30 57 PM](https://github.com/rbwendt/blender-add-mesh-fibonacci-sphere/assets/159598676/eaf39e5b-09d5-48a0-a18b-88d3bfa23ea4)

**Comment by rbwendt** [comment]
Oh thanks for that. I've updated the file.
